apply

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -2,8 +2,17 @@ name: Deploy Entire Infra
 
 on:
   push:
-    branches: [feat-dev]
+    branches: [main, feat-dev]
   workflow_dispatch:
+    inputs:
+      terraform_action:
+        description: 'Terraform action to run'
+        required: true
+        default: 'apply'
+        type: choice
+        options:
+          - apply
+          - destroy
 
 jobs:
   deploy:
@@ -41,35 +50,11 @@ jobs:
       working-directory: ./terraform
       run: terraform init 
 
-    - name: Terraform Plan
-      working-directory: ./terraform
-      run: terraform plan -out=tfplan
 
-    # - name: Terraform destroy
-    #   working-directory: ./terraform
-    #   run: terraform destroy -auto-approve   
-
-    - name: Terraform Apply
-      working-directory: ./terraform
-      run: terraform apply -auto-approve tfplan   
-
-    # - name: Import Existing OIDC Provider if it exists 
-    #   working-directory: ./terraform
-    #   run: |
-    #     OIDC_URL=$(aws eks describe-cluster --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} --query "cluster.identity.oidc.issuer" --output text)
-    #     ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
-    #     PROVIDER_ARN="arn:aws:iam::$ACCOUNT_ID:oidc-provider/${OIDC_URL#https://}"
-
-    #     echo "Checking if OIDC Provider needs to be imported into state..."
-    #     if ! terraform state show aws_iam_openid_connect_provider.eks >/dev/null 2>&1; then
-    #       echo "Importing existing provider: $PROVIDER_ARN"
-    #       terraform import aws_iam_openid_connect_provider.eks "$PROVIDER_ARN" || echo "Already imported or skipping..."
-    #     else
-    #       echo "OIDC Provider is already tracked in state."
-    #     fi
 
     - name: Import Existing OIDC Provider if it exists 
       working-directory: ./terraform
+      if: github.event.inputs.terraform_action != 'destroy'
       run: |
         echo "Fetching OIDC Issuer URL from EKS..."
         
@@ -82,17 +67,17 @@ jobs:
         
         # Check if the AWS CLI command itself failed (exit code not 0)
         if [ $? -ne 0 ]; then
-          echo "❌ ERROR: AWS CLI command failed with exit code $?."
+          echo "ERROR: AWS CLI command failed with exit code $?."
           echo "Please verify that your cluster name '${{ secrets.EKS_CLUSTER_NAME }}' and region '${{ secrets.AWS_REGION }}' match your active AWS infrastructure."
           exit 1
         fi
 
         # Validate the string format
         if [ -z "$OIDC_URL" ] || [[ ! "$OIDC_URL" =~ ^https:// ]]; then
-          echo "❌ ERROR: Received an invalid or empty OIDC URL: '$OIDC_URL'"
+          echo "ERROR: Received an invalid or empty OIDC URL: '$OIDC_URL'"
           exit 1
         fi
-        echo "✅ Valid OIDC Issuer URL found: $OIDC_URL"
+        echo "Valid OIDC Issuer URL found: $OIDC_URL"
 
         ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
         PROVIDER_ARN="arn:aws:iam::$ACCOUNT_ID:oidc-provider/${OIDC_URL#https://}"
@@ -106,6 +91,7 @@ jobs:
         fi
 
     - name: Clear Pre-existing Addon Conflicts
+      if: github.event.inputs.terraform_action != 'destroy'
       run: |
         aws eks delete-addon \
           --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
@@ -119,13 +105,35 @@ jobs:
 
 
 
+    - name: Terraform Plan
+      working-directory: ./terraform
+      if: github.event.inputs.terraform_action != 'destroy'
+      run: terraform plan -out=tfplan
+
+    - name: Terraform Apply
+      working-directory: ./terraform
+      if: github.event.inputs.terraform_action != 'destroy'
+      run: terraform apply -auto-approve tfplan   
+
+
+
+    - name: Terraform Plan (Destroy)
+      working-directory: ./terraform
+      if: github.event.inputs.terraform_action == 'destroy'
+      run: terraform plan -destroy -out=tfplan
+
+    - name: Terraform Destroy
+      working-directory: ./terraform
+      if: github.event.inputs.terraform_action == 'destroy'
+      run: terraform apply -auto-approve tfplan 
         
-    - name: Login to Amazon ECR
-      if: ${{ github.event.inputs.terraform_action != 'destroy' }}
+    - name: Login to Amazon ECR 
+      if: github.event.inputs.terraform_action != 'destroy'
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
 
     - name: Build, Tag and Push image to ECR (User)
+      if: github.event.inputs.terraform_action != 'destroy'
       id: build-user-service
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
@@ -139,6 +147,7 @@ jobs:
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
 
     - name: Build, Tag and Push image to ECR (Transaction)
+      if: github.event.inputs.terraform_action != 'destroy'
       id: build-transaction-service
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
@@ -152,6 +161,7 @@ jobs:
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
 
     - name: Build, Tag and Push image to ECR (Activity)
+      if: github.event.inputs.terraform_action != 'destroy'
       id: build-activity-service
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
@@ -165,6 +175,7 @@ jobs:
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
 
     - name: Build, Tag and Push image to ECR (Postgres Init)
+      if: github.event.inputs.terraform_action != 'destroy'
       id: build-postgres-service
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
@@ -178,17 +189,20 @@ jobs:
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
 
     - name: Install Ansible
+      if: github.event.inputs.terraform_action != 'destroy'
       run: |
         python3 -m pip install --upgrade pip
         python3 -m pip install ansible boto3 botocore
 
     - name: Install kubectl
+      if: github.event.inputs.terraform_action != 'destroy'
       run: |
         curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
         chmod +x kubectl
         sudo mv kubectl /usr/local/bin/
 
     - name: Install eksctl
+      if: github.event.inputs.terraform_action != 'destroy'
       run: |
         curl --silent --location \
           "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" \
@@ -196,12 +210,14 @@ jobs:
         sudo mv /tmp/eksctl /usr/local/bin
 
     - name: Get Nginx public IP
+      if: github.event.inputs.terraform_action != 'destroy'
       id: nginx-ip
       working-directory: ./terraform
       run: |
         echo "NGINX_IP=$(terraform output -raw nginx_public_ip)" >> $GITHUB_OUTPUT
 
     - name: Save SSH private key
+      if: github.event.inputs.terraform_action != 'destroy'
       env:
         SSH_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
       run: |
@@ -210,6 +226,7 @@ jobs:
         chmod 600 /home/runner/.ssh/ansible_key.pem
 
     - name: Wait for EC2 to be ready
+      if: github.event.inputs.terraform_action != 'destroy'
       run: |
         for i in {1..12}; do
           ssh -i /home/runner/.ssh/ansible_key.pem \
@@ -222,6 +239,7 @@ jobs:
         done
 
     - name: Map EC2 IAM identity inside EKS
+      if: github.event.inputs.terraform_action != 'destroy'
       run: |
         aws eks update-kubeconfig \
           --name ${{ secrets.EKS_CLUSTER_NAME }} \
@@ -236,6 +254,7 @@ jobs:
           --no-duplicate-arns
 
     - name: Create Ansible inventory
+      if: github.event.inputs.terraform_action != 'destroy'
       run: |
         cat > ansible/hosts.ini <<EOF
         [nginx]
@@ -250,6 +269,7 @@ jobs:
         EOF
 
     - name: Run Ansible playbook
+      if: github.event.inputs.terraform_action != 'destroy'
       run: |
         ANSIBLE_CONFIG=ansible/ansible.cfg \
         ansible-playbook ansible/playbook.yml \
@@ -284,6 +304,7 @@ jobs:
     #     echo "activity_lb=$ACTIVITY_LB" >> "$GITHUB_OUTPUT"
 
     - name: Get Load Balancer URLs
+      if: github.event.inputs.terraform_action != 'destroy'
       id: get-lb-urls
       run: |
         aws eks update-kubeconfig \
@@ -321,6 +342,7 @@ jobs:
         echo "Activity LB: $ACTIVITY_LB"
 
     - name: Update frontend API endpoints
+      if: github.event.inputs.terraform_action != 'destroy'
       working-directory: ./techbleat-global-bank-frontend
       run: |
         sed -i 's|const USER_API = "http://[^"]*";|const USER_API = "http://${{ steps.get-lb-urls.outputs.user_lb }}:8000";|' src/App.jsx
@@ -328,6 +350,7 @@ jobs:
         sed -i 's|const ACTIVITY_API = "http://[^"]*";|const ACTIVITY_API = "http://${{ steps.get-lb-urls.outputs.activity_lb }}:8001";|' src/App.jsx
 
     - name: Build, Tag and Push frontend image to ECR
+      if: github.event.inputs.terraform_action != 'destroy'
       id: build-frontend-service
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
@@ -342,6 +365,7 @@ jobs:
 
 
     - name: Run Ansible playbook
+      if: github.event.inputs.terraform_action != 'destroy'
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
